### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by hasinaattaullah** [computationalprivacy/CorrectMatch.jl#1]
I need some information related to the CorrectMatch module which is in Julia. Will, it runs in windows as I have installed Julia and I have added CorrectMatch.jl module, but I cannot access it from python. I am using windows 10 with Anaconda (spyder) for python.

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-61b0b579af67> in <module>
----> 1 import toounique
      2 toounique.precompile()
      3 
      4 import numpy as np
      5 import pandas as pd

ModuleNotFoundError: No module named 'toounique'

**Comment by cynddl** [comment]
Thanks! The module name has been fixed in https://github.com/computationalprivacy/pycorrectmatch/blob/master/demo/demonstration-notebook.ipynb

Can you follow the instructions at https://github.com/computationalprivacy/pycorrectmatch and let me know if it works now?

**Comment by hasinaattaullah** [comment]
Yes, it is solved now.
Thank you
