### ISSUE TITLE
Does it correlate range of values?

### ISSUE THREAD

**Issue by hasinaattaullah** [computationalprivacy/CorrectMatch.jl#5]
I just want to know if it works with range of values?
For example if we are working with generalized tables, we have medical data and we are generalizing age of some specific group as [35-50] will it correlate these values?

**Comment by cynddl** [comment]
Hi @hasinaattaullah, I'm not sure I understand what you mean. Do you mean _age = 35–50_ as a group or any age between 35 and 50 ? The code works by building a generative model from your data, so it will reflect what your data looks like.

**Comment by hasinaattaullah** [comment]
Thanks for your response.
Yes I mean age 35-50 as a group,
For example my data is like ;
age            zip                     gender      Disease      group
24-35         3333-4444          M             abc             1
24-35         3333-4444          F                xyz             1
38-45          111-222              F             xyz              2
38-45           111-222             M            dcf              2

So does it work with these, in this case age and zip are string values. So you mean to say that it builds generative model from our data so it definitely take these values. (am I right?)
